export const SOME_THING_WENT_WRONG = 'SOME_THING_WENT_WRONG';

export const QUESTION_DOES_NOT_EXIST = 'QUESTION_DOES_NOT_EXIST';

export const PROMPT_IS_REQUIRED = 'PROMPT_IS_REQUIRED';
export const TITLE_DOES_NOT_EXIST = 'TITLE_DOES_NOT_EXIST';
